global:
  default:
    interval: 1
    color:
      fg: "#577590"
      value: "#B3541E"
      label: "#774360"
      bg: "#1A1A2E"
  layout:
    default:
      px_height: 20
      mode: composition
      font: DejaVu Sans Mono-12
    bc:
      scraper:
        - localtime_view
      width: 220
      align: c
    bl:
      scraper:
        - workspace_view
      align: l
      is_dock: 1
    br:
      scraper:
        - lvm_stats
        - cpu_stats
        - memory_stats
        - wifi_stats
      align: r

cpu_stats:
  interval: 5

localtime_view:
  interval: 1
  color:
    value: "#774360"

memory_stats:
  interval: 5

lvm_stats:
  interval: 5
  dm_map:
    dm-0: /home
    dm-1: /root
    dm-3: /tmp
    dm-4: /var

wifi_stats:
  interval: 5
  interface: wlan0

workspace_view:
  interval: 0.3
