defaults:
  scraper:
    interval: 5
    color:
      value: "#b57614" # $yellow_mute
      label: "#bdae93" # $pale5
  group:
    px_height: 20
    mode: composition
    font: TX\-02\ Thin-12
    color:
      fg: "#bdae93" # $pale5
      bg: "#1d2021" # $dark0

group:
  bc:
    scraper:
      - localtime_view
    width: 220
    align: c
  bl:
    scraper:
      - audiovol_view
      - workspace_view
    align: l
    is_dock: 1
  br:
    scraper:
      - volume_stats
      - cpu_stats
      - memory_stats
      - net_stats
    align: r

scraper:
  cpu_stats:
    interval: 1

  localtime_view:
    interval: 1

  memory_stats:

  # device_conf:
  #   key := fs mountpoint
  #   value := {
  #     label := display value
  #     show := {feature toggles}
  #   }
  #
  volume_stats:
    interval: 2
    device_conf:
      /home:
        label: /home
        show:
          io_load: true
          # space_used: true
      /:
        label: /root
        show:
          io_load: true
          # space_used: true
      /boot:
        label: /boot
        show:
          # space_used: true
      /var:
        label: /var
        show:
          io_load: true
          # space_used: true
      /tmp:
        label: /tmp
        show:
          io_load: true

  # device_conf:
  #   key := interface id
  #   value := {
  #     label := display value
  #     show := {feature toggles}
  #   }
  #
  net_stats:
    interval: 2
    device_conf:
      wlan0:
        label: wlan0
        show:
          io_load: true

  workspace_view:
    interval: 0.3

  audiovol_view:
