FROM python:bookworm

# https://docs.sympy.org/latest/reference/index.html
# https://docs.scipy.org/doc/scipy/reference/index.html
RUN python -m pip install sympy scipy

# https://github.com/piccolomo/plotext/
RUN python -m pip install plotext

# https://galois.readthedocs.io/en/v0.4.1/api/
# https://github.com/hellman/libnum/
# https://gmpy2.readthedocs.io/en/latest/
# https://github.com/ethereum/py_ecc
RUN python -m pip install galois libnum gmpy2 py_ecc







