load_posher color

# simple newline print with optional prefix tag
ramble() {
    prefix="${2:-}"
    [ -n "$prefix" ] && prefix="$prefix "
    printf "%s%s\n" "$prefix" "$1"
}

__whitespace_pad_worker() {
    _posher_txt=${1-}
    _posher_char_count=${#_posher_txt}
    _posher_max_len=${2:-$_posher_char_count}
    _posher_left=;
    [ "$_posher_char_count" -ge "$_posher_max_len" ] \
      && return $__EXCODE_GENERAL

    _posher_left=$(( (_posher_max_len - _posher_char_count) / 2 ))
    printf '%*s%s%*s' \
        "$_posher_left" ''   \
        "$_posher_txt"       \
        "$(( _posher_max_len - _posher_char_count - _posher_left ))" ''
}

__whitespace_pad() {
    _posher_tag_padded=$(__whitespace_pad_worker "$1" 4) || :
    unset _posher_txt _posher_char_count _posher_max_len _posher_left

    _posher_tag_styled=$(hue "${_posher_tag_padded:-$1}" "$2" bold) || :
    unset _posher_tag_padded

    printf '[%s]' "${_posher_tag_styled:-$1}";
}

__set_status_outcome() {
    stdoutln "$(__whitespace_pad "$1" "$2")" $(hue "${3-}" gray) \
      && _posher_retval=$? || _posher_retval=$?
    unset _posher_tag_styled

    return $_posher_retval
}

# $1: optional txt -> sneak in relevant info after execution step resolved
status_ok()     { __set_status_outcome FINE  lightgreen  "${1-}" ;}
status_warn()   { __set_status_outcome WARN  yellow      "${1-}" ;}
status_fail()   { __set_status_outcome FAIL  red         "${1-}" ;}
status_info()   { __set_status_outcome INFO  lightblue   "${1-}" ;}

# Convenience function to get charcount for a string.
# Inline it directly if the length must be captured in a hot loop
strlen() { [ $# -eq 0 ] && stdoutln 0 || stdoutln "${#1}" ;}

# get the visible char length of a string that might include
# ansi colors/styles control sequences
strlen_frfr() { set -- "$(ansi_stripper "${1-}")" && stdoutln ${#1} ;}

__statusline_worker() {
    _posher_status_msg=${1-}
    [ -z "${2-}" ] \
      && _posher_status_msg=" - $_posher_status_msg"

    # default terminal width 80 columns, 6 chars reserved for outcome status
    _posher_dots_needed=$(( 74 - $(strlen_frfr "$_posher_status_msg") ))
    while [ $_posher_dots_needed -gt 0 ]; do
        _posher_status_msg="${_posher_status_msg}."
        _posher_dots_needed=$(( _posher_dots_needed - 1))
    done

    stdout "$_posher_status_msg"
}

# $1: the status message
# $2: if non-empty, disables indendation of the status message
#
# wraps step execution with the corresponding outcome indicators
# generated by status_ok, status_warn, and status_fail. Makes it easy to
# expose helpful information to the user during sequential multistep logic
statusline() {
    __statusline_worker "$@" && _posher_retval=$? || _posher_retval=$?
    unset _posher_status_msg _posher_dots_needed
    return $_posher_retval
}

# shortcut for a state independent `statusline && status_info`. Useful for state transitions
infoline() {
    statusline  "${1-}" disable_indent \
      && status_info "${2-}"
}

throw() {
    _posher_msg=${1-NO_MSG_SUPPLIED}
    _posher_retval=${2:-$__EXCODE_GENERAL}

    _posher_fatal_tag=$(hue FATAL red bold) || :

    stderrln "[${_posher_fatal_tag:-FATAL}]" "$_posher_msg" \
      || :

    _posher_sigfile="$(get_sigfile_p)" 2>/dev/null          \
      && printf '%d' "$_posher_retval" > "$_posher_sigfile" \
      || :

    exit $_posher_retval
}

# general purpose printers
_shared_rambling_fmt() { stdoutln "[$(hue $2 $3)]" "$1" ;}

yell()  { _shared_rambling_fmt "$1" crit red >&2      ;}
bless() { _shared_rambling_fmt "$1" succ lightgreen   ;}
hint()  { _shared_rambling_fmt "$1" hint lightyellow  ;}
tell()  { _shared_rambling_fmt "$1" info white        ;}
